apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-web.fullname" . }}
  labels:
  {{- include "demo-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      #      targetPort: 8080
      {{- if eq "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
  {{- include "demo-web.selectorLabels" . | nindent 4 }}
